name = "All the Mods 9 - FIX"
author = "hmjn023"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ececd0251d88e59db77eec74788e9ae8b34676313295a98cbfd48f1823b36f6"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
