name = "All the Mods 9 - FIX"
author = "hmjn023"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83d111565ea5e865e7d85d520f7c3576e787b859c0a322aaeaa8bfa3658fa44e"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
